// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4.team4ascent.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4.team4ascent.Robot;
import org.usfirst.frc4.team4ascent.subsystems.Chasis;
/**
 *
 */
public class  DriveStraight extends Command {
    
    private final double speed;
    private final double distance;
    
    public DriveStraight(double speed, double distance) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chasis);
        
        this.speed = speed;
        this.distance = distance;
  
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    public DriveStraight(double distance) {
        this(-.5, distance);
    }
    
    public DriveStraight() {
        this(0);
    }
   
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
       Robot.chasis.setSpeed(-.5);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
